// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication5.Models;

namespace WebApplication5.Migrations
{
    [DbContext(typeof(UitContext))]
    [Migration("20180702113041_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication5.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChapterName");

                    b.Property<int?>("SubjectID");

                    b.HasKey("ChapterID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("WebApplication5.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChapterID");

                    b.Property<string>("Text");

                    b.Property<string>("TextMathematica");

                    b.Property<string>("TextPython");

                    b.HasKey("QuestionID");

                    b.HasIndex("ChapterID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("WebApplication5.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("WebApplication5.Models.Chapter", b =>
                {
                    b.HasOne("WebApplication5.Models.Subject")
                        .WithMany("Chapter")
                        .HasForeignKey("SubjectID");
                });

            modelBuilder.Entity("WebApplication5.Models.Question", b =>
                {
                    b.HasOne("WebApplication5.Models.Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterID");
                });
#pragma warning restore 612, 618
        }
    }
}
